### ISSUE TITLE
Crash when taking off stomping boots

### ISSUE THREAD

**Issue by Ardub23** [NullCGT/SpliceHack#71] opened 2020-05-17 06:52 UTC
Playing 0.7.1-20 on the Hardfought server. My game crashes when taking off a pair of stomping boots. However, taking off the boots while levitating does _not_ crash the game.

The save file can be recovered, so I was able to try a few times, and I caught the following screenshot in the brief moment before being booted back to the server menu:
![SpliceHack stomping boots crash](https://user-images.githubusercontent.com/48235540/82137448-5c43d900-97d5-11ea-87d2-d8ef2b9032da.png)

After a bit of source diving, I found that [do_wear.c line 260](https://github.com/NullCGT/SpliceHack/blob/Master/src/do_wear.c#L260) anomalously references `uarmf->otyp` while the other auto-identifying boots in Boots_off() use only `otyp`. If this isn't the source of the problem, then it's something I don't understand.

**Comment by NullCGT** [comment] 2020-05-17 14:42
Thanks for the report! 

The issue is exactly what you pointed out. Fixed in the master branch.

**Closed by NullCGT** 2020-05-17 14:42 UTC
