### ISSUE TITLE
Monsters on Astral can offer the Amulet when not on an altar

### ISSUE THREAD

**Issue by enetics-secker** [NullCGT/SpliceHack#61] opened 2020-01-22 00:26 UTC
Had the amulet stolen by Izchak the Nomad turn 66728. 1 turn later, while he was standing next to me he offered the amulet and ascended. I was still in the entry area of Astral.  ttyrec [here](https://www.hardfought.org/userdata/b/bouquet/splicehack/ttyrec/2020-01-21.23:56:19.ttyrec.gz)

**Comment by NullCGT** [comment] 2020-01-23 04:04
This one took a lot of puzzling.

It turns out that the monster offering code itself is working just fine. The problem is that a few player monsters were flagged improperly, which caused them to be treated as covetous. What happened in your game is that the Nomad stole from you, started fleeing, and warped somewhere else in the level. Against all odds, it happened to warp onto a coaligned high altar, then proceeded to sacrifice the amulet and instantly end the game. Wow.

Your run officially counts as an ascension in my book.

Fixed via d55a379.

**Closed by NullCGT** 2020-01-23 04:04 UTC
