### ISSUE TITLE
Shopkeeper Services Interact Strangely With Credit and $: 0

### ISSUE THREAD

**Issue by NickASabo** [NullCGT/SpliceHack#113] opened 2020-10-04 03:56 UTC
Very minor issue. Shopkeepers can use credit for their services, and this works insofar as the payment goes through, and the shopkeeper is not angry or think you owe them, and the program does not crash. But, if you have 0 money and are buying on credit, results in the message:

This price is deducted from your credit. zero payment in money2mon!
Program in disorder! (Saving and reloading may fix this problem.)
Please report these messages to AntiGulp.

**Comment by NullCGT** [comment] 2020-10-11 20:04
This took a little while to figure out. It turns out that the root cause was a slight difference in SLASH'EM and 3.7 shopkeeper code.

I've resolved this in development, and will close this issue when it is merged into master.

**Closed** 2020-10-23 02:21 UTC
