### ISSUE TITLE
Furnace, more info crash

### ISSUE THREAD

**Issue by tempestnano** [NullCGT/SpliceHack#35] opened 2018-10-13 04:32 UTC
When I look at a furnace and choose "More info", the game crashes wiping out save files. I have reproduced this twice in two different games.

Version: b634fe93386bf7d4769f8ab1efe671c332a90ce7
Server: Hardfought

**Comment by NullCGT** [comment] 2018-10-13 22:57
I was unable to reproduce this, but I added a database entry for furnaces, which should hopefully address the issue.

Note that this repository will be closed, and will be moving to here: https://github.com/NullCGT/SpliceHack-NetHack

**Closed** 2018-10-20 13:39 UTC
