### ISSUE TITLE
Bug: Uncursed tin openers weld

### ISSUE THREAD

**Issue by msearle5** [NullCGT/SpliceHack#230] opened 2022-01-04 14:11 UTC
Tin openers will weld themselves to your hand as if they were cursed, even when they are not cursed.

The problem appears to be wield.c, line 71:
/* used by welded(), and also while wielding */
/* #define will_weld(optr) \
    ((optr)->cursed && (erodeable_wep(optr) || (optr)->otyp == TIN_OPENER)) */
/* Tin openers still weld. Everything else uses the new cursing system. - Kes. */
#define will_weld(optr) \
    ((optr)->otyp == TIN_OPENER)

which looks to me as if it should be ((optr)->cursed && (optr)->otyp == TIN_OPENER))

Seen playing locally on Gentoo Linux, version:
Unix NetHack Version 1.1.0-1 Beta - last build Wed Dec 29 02:41:11 2021
(b29334720e353ee991bba3e657d22bacbe78a523,branch:Spl-R-1.1.0).

**Comment by NullCGT** [comment] 2022-01-20 15:42
Yup, that looks like the root cause, all right. I've taken a break from developing while switching laptops and distros, so it's been a while, but I'll see if I can push a fix for this in the next day or so.

Thank you!

**Comment by NullCGT** [comment] 2022-02-01 18:02
Fixed via aa8c838fc44b32acc4adbaec7145b1e835af9130.

**Closed by NullCGT** 2022-02-01 18:02 UTC
Labels: bug
